// Índice de poderes do Tormenta 20 (livro básico, cap. 2), conferido nas tabelas do livro.
// Categorias: Combate, Destino, Magia, Tormenta (os Concedidos são gerados a partir das
// divindades em catalog.ts). Nome + pré-requisito para todos; descrição (essencial
// mecânico) preenchida para os Poderes de Combate; demais descrições ficam para depois.

export type PowerCategory = "Combate" | "Destino" | "Magia" | "Concedido" | "Tormenta";
export type PowerInfo = { name: string; category: PowerCategory; prereq?: string; desc?: string };

export const POWERS_BASE: PowerInfo[] = [
  // --- Combate (40) ---
  { name: "Acuidade com Arma", category: "Combate", prereq: "Des 1", desc: "Com arma corpo a corpo leve ou de arremesso, use Destreza no lugar de Força nos ataques e no dano." },
  { name: "Ataque Poderoso", category: "Combate", prereq: "For 1", desc: "No ataque corpo a corpo, sofra –2 no teste para +5 no dano." },
  { name: "Quebrar Aprimorado", category: "Combate", prereq: "" },
  { name: "Trespassar", category: "Combate", prereq: "" },
  { name: "Combate Defensivo", category: "Combate", prereq: "Int 1", desc: "Ao agredir: até o próximo turno, –2 nos ataques e +5 na Defesa." },
  { name: "Derrubar Aprimorado", category: "Combate", prereq: "Combate Defensivo", desc: "+2 para derrubar; ao derrubar, gaste 1 PM para um ataque extra contra o alvo." },
  { name: "Desarmar Aprimorado", category: "Combate", prereq: "Combate Defensivo", desc: "+2 para desarmar; ao desarmar, gaste 1 PM para arremessar a arma do alvo para longe." },
  { name: "Empunhadura Poderosa", category: "Combate", prereq: "For 3", desc: "Usar arma de uma categoria de tamanho maior impõe só –2 (em vez de –5) nos ataques." },
  { name: "Encouraçado", category: "Combate", prereq: "proficiência com armaduras pesadas", desc: "Com armadura pesada, +2 na Defesa (+2 por outro poder que tenha Encouraçado como pré-requisito)." },
  { name: "Fanático", category: "Combate", prereq: "12º nível de personagem, Encouraçado" },
  { name: "Inexpugnável", category: "Combate", prereq: "6º nível de personagem" },
  { name: "Esquiva", category: "Combate", prereq: "Des 1", desc: "+2 na Defesa e em Reflexos." },
  { name: "Estilo Desarmado", category: "Combate", prereq: "treinado em Luta", desc: "Ataques desarmados causam 1d6 e podem ser letais ou não letais sem penalidade." },
  { name: "Estilo de Arma e Escudo", category: "Combate", prereq: "treinado em Luta, proficiência com escudos", desc: "O bônus na Defesa do escudo aumenta em +2." },
  { name: "Ataque com Escudo", category: "Combate", prereq: "Estilo de Arma e Escudo", desc: "1/rodada, ao agredir com escudo, gaste 1 PM para um ataque corpo a corpo extra sem perder o bônus de Defesa do escudo." },
  { name: "Bloqueio com Escudo", category: "Combate", prereq: "Estilo de Arma e Escudo", desc: "Ao sofrer dano, gaste 1 PM para redução igual ao bônus de Defesa do escudo contra aquele dano." },
  { name: "Estilo de Arma Longa", category: "Combate", prereq: "For 1, treinado em Luta", desc: "+2 nos ataques com armas alongadas e pode atacar alvos adjacentes com elas." },
  { name: "Piqueiro", category: "Combate", prereq: "" },
  { name: "Estilo de Uma Arma", category: "Combate", prereq: "treinado em Luta", desc: "Com uma arma corpo a corpo e a outra mão livre: +2 na Defesa e nos ataques com ela." },
  { name: "Ataque Preciso", category: "Combate", prereq: "Estilo de Uma Arma", desc: "Com uma arma corpo a corpo e a outra mão livre: +2 na margem de ameaça e +1 no multiplicador de crítico." },
  { name: "Estilo de Duas Armas", category: "Combate", prereq: "Des 2, treinado em Luta", desc: "Empunhando duas armas (uma leve) e agredindo, faz dois ataques (um por arma); –2 nos ataques até o próximo turno (Ambidestria remove a penalidade)." },
  { name: "Arma Secundária Grande", category: "Combate", prereq: "Estilo de Duas Armas", desc: "Pode empunhar duas armas de uma mão com o Estilo de Duas Armas." },
  { name: "Estilo de Duas Mãos", category: "Combate", prereq: "For 2, treinado em Luta", desc: "Com arma corpo a corpo nas duas mãos, +5 no dano (não vale para armas leves)." },
  { name: "Ataque Pesado", category: "Combate", prereq: "Estilo de Duas Mãos", desc: "Com arma de duas mãos, pague 1 PM: se acertar, faz derrubar ou empurrar de graça (use o ataque como teste de manobra)." },
  { name: "Estilo de Arremesso", category: "Combate", prereq: "treinado em Pontaria", desc: "Saca armas de arremesso como ação livre e +2 no dano com elas (com Saque Rápido, +2 nos ataques)." },
  { name: "Arremesso Múltiplo", category: "Combate", prereq: "Des 1, Estilo de Arremesso", desc: "1/rodada, gaste 1 PM para um ataque adicional de arremesso contra o mesmo alvo." },
  { name: "Arremesso Potente", category: "Combate", prereq: "For 1, Estilo de Arremesso", desc: "Com arma de arremesso, use Força no lugar de Destreza nos ataques; permite Ataque Poderoso com arremesso." },
  { name: "Estilo de Disparo", category: "Combate", prereq: "treinado em Pontaria", desc: "Com arma de disparo, soma a Destreza nas rolagens de dano." },
  { name: "Disparo Preciso", category: "Combate", prereq: "Estilo de Disparo ou Estilo de Arremesso", desc: "Ataques à distância contra alvos em corpo a corpo não sofrem a penalidade de –5." },
  { name: "Mira Apurada", category: "Combate", prereq: "Sab 1" },
  { name: "Disparo Rápido", category: "Combate", prereq: "Des 1, Estilo de Disparo", desc: "Ação completa para agredir com arma de disparo (recarga livre) dá um ataque adicional; –2 nos ataques até o próximo turno." },
  { name: "Finta Aprimorada", category: "Combate", prereq: "treinado em Enganação", desc: "+2 em Enganação para fintar e pode fintar como ação de movimento." },
  { name: "Foco em Arma", category: "Combate", prereq: "proficiência com a arma", desc: "Escolha uma arma: +2 nos ataques com ela (pode escolher outras vezes para armas diferentes)." },
  { name: "Ginete", category: "Combate", prereq: "Cavalgar" },
  { name: "Carga de Cavalaria", category: "Combate", prereq: "Ginete", desc: "Investida montada causa +2d8 de dano e permite continuar o movimento (em linha reta)." },
  { name: "Presença Aterradora", category: "Combate", prereq: "Intimidação" },
  { name: "Proficiência", category: "Combate", prereq: "" },
  { name: "Reflexos de Combate", category: "Combate", prereq: "Des 1" },
  { name: "Saque Rápido", category: "Combate", prereq: "Iniciativa" },
  { name: "Vitalidade", category: "Combate", prereq: "Con 1" },

  // --- Destino (20) ---
  { name: "Acrobático", category: "Destino", prereq: "Des 2" },
  { name: "Ao Sabor do Destino", category: "Destino", prereq: "6º nível de personagem" },
  { name: "Aparência Inofensiva", category: "Destino", prereq: "Car 1" },
  { name: "Atlético", category: "Destino", prereq: "For 2" },
  { name: "Atraente", category: "Destino", prereq: "Car 1" },
  { name: "Comandar", category: "Destino", prereq: "Car 1" },
  { name: "Costas Largas", category: "Destino", prereq: "Con 1, For 1" },
  { name: "Foco em Perícia", category: "Destino", prereq: "treinado na perícia escolhida" },
  { name: "Inventário Organizado", category: "Destino", prereq: "Int 1" },
  { name: "Investigador", category: "Destino", prereq: "Int 1" },
  { name: "Lobo Solitário", category: "Destino", prereq: "" },
  { name: "Medicina", category: "Destino", prereq: "Sab 1, treinado em Cura" },
  { name: "Parceiro", category: "Destino", prereq: "Adestramento ou Diplomacia, 5º nível de personagem" },
  { name: "Sentidos Aguçados", category: "Destino", prereq: "Sab 1, Percepção" },
  { name: "Sortudo", category: "Destino", prereq: "" },
  { name: "Surto Heroico", category: "Destino", prereq: "" },
  { name: "Torcida", category: "Destino", prereq: "Car 1" },
  { name: "Treinamento em Perícia", category: "Destino", prereq: "" },
  { name: "Venefício", category: "Destino", prereq: "Ofício (alquimista)" },
  { name: "Vontade de Ferro", category: "Destino", prereq: "Sab 1" },

  // --- Magia (8) ---
  { name: "Celebrar Ritual", category: "Magia", prereq: "Habilidade Magias, Misticismo ou Religião, 8º nível de personagem" },
  { name: "Escrever Pergaminho", category: "Magia", prereq: "Habilidade Magias, Ofício (escriba)" },
  { name: "Foco em Magia", category: "Magia", prereq: "Lançar magias" },
  { name: "Magia Acelerada", category: "Magia", prereq: "Lançar magias de 2º círculo" },
  { name: "Magia Ampliada", category: "Magia", prereq: "Lançar magias" },
  { name: "Magia Discreta", category: "Magia", prereq: "Lançar magias" },
  { name: "Magia Ilimitada", category: "Magia", prereq: "Lançar magias" },
  { name: "Preparar Poção", category: "Magia", prereq: "Habilidade Magias, Ofício (alquimista)" },

  // --- Tormenta (22) ---
  { name: "Anatomia Insana", category: "Tormenta", prereq: "" },
  { name: "Legião Aberrante", category: "Tormenta", prereq: "Três poderes da Tormenta" },
  { name: "Antenas", category: "Tormenta", prereq: "" },
  { name: "Armamento Aberrante", category: "Tormenta", prereq: "Um poder da Tormenta" },
  { name: "Articulações Flexíveis", category: "Tormenta", prereq: "" },
  { name: "Asas Insetoides", category: "Tormenta", prereq: "Quatro poderes da Tormenta" },
  { name: "Carapaça", category: "Tormenta", prereq: "" },
  { name: "Corpo Aberrante", category: "Tormenta", prereq: "Um poder da Tormenta" },
  { name: "Cuspir Enxame", category: "Tormenta", prereq: "" },
  { name: "Dentes Afiados", category: "Tormenta", prereq: "" },
  { name: "Larva Explosiva", category: "Tormenta", prereq: "" },
  { name: "Desprezar a Realidade", category: "Tormenta", prereq: "Quatro poderes da Tormenta" },
  { name: "Empunhadura Rubra", category: "Tormenta", prereq: "" },
  { name: "Fome de Mana", category: "Tormenta", prereq: "" },
  { name: "Mãos Membranosas", category: "Tormenta", prereq: "" },
  { name: "Membros Estendidos", category: "Tormenta", prereq: "" },
  { name: "Membros Extras", category: "Tormenta", prereq: "Quatro poderes da Tormenta" },
  { name: "Mente Aberrante", category: "Tormenta", prereq: "" },
  { name: "Olhos Vermelhos", category: "Tormenta", prereq: "" },
  { name: "Pele Corrompida", category: "Tormenta", prereq: "" },
  { name: "Sangue Ácido", category: "Tormenta", prereq: "" },
  { name: "Visco Rubro", category: "Tormenta", prereq: "" },
];
