spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portalrpg
    username: portalrpg
    password: portalrpg
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    com.portalrpg: DEBUG
